# TensorFlow Basic Computation

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(f'TensorFlow version: {tf.__version__}')

TensorFlow version: 2.3.1


In [3]:
# Basic computation

a = tf.constant(3.0)
b = tf.constant(4.0)
c = tf.sqrt(a ** 2 + b ** 2)
print(f'{c=}')

c=<tf.Tensor: shape=(), dtype=float32, numpy=5.0>


In [4]:
# Numpy representation

print(c.numpy())
print(type(c.numpy()))

5.0
<class 'numpy.float32'>


In [5]:
# Vector dot product

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.tensordot(a, b, axes=[0, 0])
print(f'{c}')

32


In [6]:
# Matrix multiplication in Numpy

A0 = np.random.randn(3, 3)
B0 = np.random.randn(3, 1)
C0 = A0.dot(B0)
print(f'{C0}')

[[-0.64247673]
 [-0.74327568]
 [ 0.90092455]]


In [7]:
# Matrix multiplication in TensorFlow

A = tf.constant(A0)
B = tf.constant(B0)
C = tf.matmul(A, B)
print(f'{C}')

[[-0.64247673]
 [-0.74327568]
 [ 0.90092455]]


In [8]:
# Broadcasting

A = tf.constant([[1, 2], [3, 4]])
b = tf.constant(1)
C = A + b
print(f'{C}')

[[2 3]
 [4 5]]


In [9]:
# Element-wise multiplication

A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[2, 3], [4, 5]])
C = A * B
print(f'{C}')

[[ 2  6]
 [12 20]]
